export const userActionTypes = {
  SET_USER: 'SET_USER',
  ONE_DOLLAR_PAYMENT: 'ONE_DOLLAR_PAYMENT',
  SET_TASK: 'SET_TASK',
  SET_TASK_ID:'SET_TASK_ID',
  DELETE_TASK: 'DELETE_TASK',
  SAVE_TASK: 'SAVE_TASK',
  GET_FROM_LOCAL_STORAGE: 'GET_FROM_LOCAL_STORAGE',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGIN_USER: 'LOGIN_USER'
}
